spring:
  jpa:
    show-sql=true
    properties.hibernate.format_sql=true
    hibernate.ddl-auto=update
  
  sleuth.sampler.probability=1.0
  zipkin.baseurl=http://localhost:9411

server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka


# exposing acutator endpoints
management.endpoints.web.exposure.include: "*"