spring.application.name: location-service

spring:
  jpa:
    show-sql=false
    hibernate.ddl-auto=none
  
  sleuth.sampler.probability=0.1
  zipkin.baseurl=http://localhost:9411

server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka