spring:
  application:
    name: user-service
  
  jpa:
    show-sql: false
    hibernate.ddl-auto: none

  sleuth.sampler.probability:  0.1
  zipkin.baseurl: http://localhost:9411


eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

# logging properties
logging:
  level:
    com.ticketapp.userservice: warn