spring:
  application:
    name: user-service
  
  jpa:
    show-sql: true
    properties.hibernate.format_sql: true
    hibernate.ddl-auto: update

  sleuth.sampler.probability:  1.0
  zipkin.baseurl: http://localhost:9411


eureka.client.serviceUrl.defaultZone: http://localhost:8761/eureka

# logging properties
logging:
  level:
    com.ticketapp.userservice: TRACE

# exposing acutator endpoints
management.endpoints.web.exposure.include: "*"